// Enums for Order
export enum OrderStatus {
  PENDING = 'PENDING',
  CANCELED = 'CANCELED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  RECEIVED = 'RECEIVED',
  COMPLETED = 'COMPLETED',
  RETURNED = 'RETURNED',
}

// Group: PENDING
//  - PENDING
// Group: PROCESSING
//  - ACCEPTED
//  - DELIVERING
//  - DELIVERED
// Group: COMPLETED
//  - RECEIVED
//  - COMPLETED
// Group: REJECTED
//  - REJECTED
// Group: RETURNED
//  - RETURNED
